# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    increment_build_number(xcodeproj: "maxswim.xcodeproj")
    commit_version_bump(
      message: "Increment build number",
      xcodeproj: "maxswim.xcodeproj",
	  force: true
    )
    push_to_git_remote
    build_app(workspace: "maxswim.xcworkspace", scheme: "maxswim")
    upload_to_testflight(
      skip_waiting_for_build_processing: true,
      apple_id: "1553445049"
    )
  end
end
