const strings = {
  home: {
    screenTitle: 'Главный',
    counterButtonTitle: 'Counter +1',
    counterText: 'Current count is ',
  },
  addLearner: {
    screenTitle: 'Добавить ученика',
    information: 'Информация',
    telephones: 'Телефоны',
    subscription: 'Абонемент',
    main: 'Основной',
    active: 'активный',
    surname: 'Фамилия',
    name: 'Имя',
    patronymic: 'Отчество',
    date: 'Дата рождения',
    note: 'Примечание',
    contactName: 'Имя контакта',
    number: 'Номер',
    telephoneExampleNumber: '+7-917-231-74-13',
    telephoneExampleName: 'Остапова Инна Михайловна',
    addNumber: 'Добавить еще',
    lessonsNumber: 'Другое количество',
    createContact: 'Создать',
    error: 'Неверное значение!',
  },
  card: {
    allLessons: 'Всего занятий',
    attendance: 'Посещаемость',
    call: 'Позвонить',
    edit: 'Редактировать',
    noLessons: 'Нет занятий',
    lessThenFive: 'Занятия',
    moreThenFive: 'Занятий',
  },
  cardTest: {
    name: 'Иванов Иван Иванович',
    lessons: 'Занятий',
  },
  phoneAuthorization: {
    screenTitle: 'Авторизация',
    logo: 'maxSwim',
    phonePlaceholder: 'Номер телефона',
    login: 'Войти',
    code: 'Введите код из СМС',
    codePlaceholder: 'Код',
    sendCodeAgain: 'Отправить еще раз',
  },
};

export default strings;
